---
name: Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:

      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 3

      - name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
